import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import { useRecoilState, useSetRecoilState } from 'recoil'
import InputBox from '../components/inputBox'
import PokectList from '../components/poketList'
import { initPoketmonList, searchValueAtom } from '../Util/recoil/state'
import { getPoketmonType, PokectmonListType } from '../types';
import { useQuery } from '@apollo/client';
import { GET_POKETMONS } from '../gql'

const Home: NextPage<{data: getPoketmonType}> = ({data}) => {
  const setInitPoketmonList = useSetRecoilState(initPoketmonList);
  setInitPoketmonList(data.findAll);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <InputBox />
      <PokectList data={data}  />
    </>
  )
}

export const getStaticProps:GetStaticProps = () => {
  const searchValue = useRecoilState(searchValueAtom);
  
  const { data:POKETLIST , loading, error } = useQuery<getPoketmonType>(
      GET_POKETMONS,
      searchValue 
      ? {
          variables: {
          isAdult: false,
          type: 'POKECT',
          search: searchValue,
          } 
      }   
      : {
          variables: {
          isAdult: false,
          type: 'POKECT',
          }
      } 
  );
  if (loading) {return <h2>Loading...</h2>}
  if (error) {return <h1>에러 발생</h1>}
  
  
  return {
      props: {
          data:POKETLIST
      }
  }
}

export default Home
