import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import InputBox from '../components/inputBox'
import PokectList from '../components/poketList'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <InputBox />
      <PokectList />
    </div>

     
  )
}

export default Home
